<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

In Lab 4.1.1 we were able to predict house price via a predictor variable from first principles. Here we the see how the same can be done using scikit-learn.

For comparison purposes, we will continue with the same predictor `sq__ft` in our dataset as last time.

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [5]:
import pandas as pd
import numpy as np
import pandas as pd

%matplotlib inline

### 1. Read in the data

In [15]:
# Read CSV
house_csv = r'C:\Users\pabarca\OneDrive - GRUPO GRANSOLAR\Desktop\IOD - Python\DATA\Sacramento_transactions.csv'
data = pd.read_csv(house_csv)

In [17]:
data.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

### 2. Predict Price

We are going to predict the target variable `price` from `sq__ft` using sklearn's linear_model.

Read up on the following methods and attributes here: [sklearn.linear_model.LinearRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)

- coef_
- intercept_
- fit()
- predict()
- score()

In [13]:
# import the LinearRegression class from the sklearn.linear_model module
from sklearn.linear_model import LinearRegression

#### 2.1 Create an instance of LinearRegression.

In [19]:
# ANSWER
linreg = LinearRegression()

#### 2.2 Fit predictor and target variables using linear regression

In [21]:
X = data['sq__ft'].values.reshape(-1,1)
y = data['price']

In [23]:
# ANSWER
linreg.fit(X,y)

LinearRegression()

#### 2.3. Using attributes of the LinearRegression() class find coefficient and intercept.

In [25]:
# ANSWER

print(linreg.coef_, linreg.intercept_)

[54.15863969] 162930.16140699777


#### 2.4 Find R^2 Score

Find $R^2$ Using the ```score``` method of LinearRegression.

In [27]:
# ANSWER
linreg.score(X, y)

0.11148717682951437

### 3. Splitting Data


Splitting the data into training and test sets is important in supervised learning.

- We ensure that the test set remains untouched during the model training process. This isolation prevents any information leakage about the test set into the training process.

- It allows us to evaluate the performance of our machine learning model on unseen data.


In [31]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Use the `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [33]:
# ANSWER
## Create training and testing subsets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


In [41]:
y_test

116    299000
609     65000
722    228750
820    380000
208    165000
        ...  
211    175000
20     122000
561      4897
920    169000
811    350000
Name: price, Length: 197, dtype: int64

In [43]:
y_train

777    300000
279    300000
496    313138
202    156000
281    300000
        ...  
943    198000
787    311518
551    677048
844    475000
304    399000
Name: price, Length: 788, dtype: int64

In [45]:
X_test

array([[1520],
       [1080],
       [2126],
       [1727],
       [1392],
       [2382],
       [1578],
       [ 795],
       [   0],
       [   0],
       [1289],
       [ 810],
       [1512],
       [   0],
       [1744],
       [1811],
       [   0],
       [2258],
       [2205],
       [1080],
       [1189],
       [ 611],
       [1306],
       [1904],
       [   0],
       [2660],
       [1261],
       [   0],
       [   0],
       [2504],
       [ 904],
       [ 796],
       [ 904],
       [1800],
       [1172],
       [   0],
       [3670],
       [1009],
       [1302],
       [1714],
       [1127],
       [1011],
       [ 852],
       [ 800],
       [1479],
       [1193],
       [ 960],
       [ 868],
       [1338],
       [1428],
       [ 962],
       [1936],
       [1166],
       [1676],
       [1609],
       [1540],
       [ 936],
       [   0],
       [1549],
       [1596],
       [1587],
       [1240],
       [1039],
       [1478],
       [1196],
       [3984],
       [  

In [39]:
X_train

array([[1623],
       [   0],
       [1394],
       [1104],
       [2307],
       [1410],
       [1358],
       [1448],
       [1249],
       [1089],
       [1686],
       [1887],
       [1302],
       [1229],
       [1120],
       [   0],
       [1678],
       [2213],
       [1362],
       [1595],
       [   0],
       [1320],
       [1152],
       [1477],
       [   0],
       [   0],
       [1144],
       [2581],
       [   0],
       [   0],
       [1319],
       [1280],
       [1830],
       [1329],
       [ 975],
       [   0],
       [1871],
       [   0],
       [1177],
       [   0],
       [1943],
       [   0],
       [   0],
       [1088],
       [1018],
       [   0],
       [1410],
       [2163],
       [1120],
       [   0],
       [ 484],
       [1430],
       [1795],
       [1406],
       [2166],
       [1320],
       [   0],
       [ 834],
       [1100],
       [ 950],
       [3433],
       [2049],
       [ 998],
       [   0],
       [2159],
       [1039],
       [26

#### 3.2 Check Shape, Sample of Test Train Data

In [67]:
# ANSWER
## Check training/test data
print(type(X_train))
print(X_train.shape)
print(X_train[:10])

print(type(y_train))
print(y_train.shape)
print(y_train[:10])

<class 'numpy.ndarray'>
(788, 1)
[[1623]
 [   0]
 [1394]
 [1104]
 [2307]
 [1410]
 [1358]
 [1448]
 [1249]
 [1089]]
<class 'pandas.core.series.Series'>
(788,)
777    300000
279    300000
496    313138
202    156000
281    300000
497    316630
647    158000
83     236000
885    112500
951    205000
Name: price, dtype: int64


In [69]:
print(type(X_test))
print(X_test.shape)
print(X_test[:10])

print(type(y_test))
print(y_test.shape)
print(y_test[:10])

<class 'numpy.ndarray'>
(197, 1)
[[1520]
 [1080]
 [2126]
 [1727]
 [1392]
 [2382]
 [1578]
 [ 795]
 [   0]
 [   0]]
<class 'pandas.core.series.Series'>
(197,)
116    299000
609     65000
722    228750
820    380000
208    165000
451    236000
681    190000
954    207973
575      4897
121    320000
Name: price, dtype: int64


#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [71]:
# ANSWER
linreg = LinearRegression()
linreg.fit(X_train, y_train)
print(linreg.coef_, linreg.intercept_)

[49.97656592] 169839.80634439248


In [73]:
# ANSWER
linreg.score(X_test, y_test)

0.15749624879281954

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using the linear regression model.**

In [79]:
# ANSWER
beta0 = linreg.intercept_
beta1 = linreg.coef_
x=1204

Ypred  = beta1*x + beta0
print(Ypred[0])


230011.59170955516


In [81]:
x=[[1204]]
Ypred=linreg.predict(x)

print(Ypred[0])

230011.59170955516


#### Find the mean squared error

In [ ]:
# Predict prices from X_test, then compare with y_test to find the mean squared error

In [85]:
y_preds=linreg.predict(X_test)
y_preds[:10]

array([245804.18653961, 223814.49753573, 276089.98548587, 256149.33568462,
       239407.18610212, 288883.98636085, 248702.82736285, 209571.17624913,
       169839.80634439, 169839.80634439])

In [87]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, y_preds, squared=True)

C:\Users\pabarca\AppData\Local\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


16280436305.076092

### Conclusion
We have seen that through scikit-learn, minimal code is needed to implement and evaluate a linear regression model.



---



---



> > > > > > > > > © 2024 Institute of Data


---



---



